### ISSUE TITLE
Gardening API attached to its Modal

### ISSUE THREAD

**Issue by wol42verine** [wol42verine/Project-1#14]
We should discuss this in Zoom, but the opengarden api had many options for data to be displayed in the modal.

**Comment by MarynaMartseniuk** [comment]
Let's attach plant info. We already made a decision on that as far as I got. After we practice on this then we can anything we decide. What do you guys think?

**Comment by MarynaMartseniuk** [comment]
I would do this way:

from https://openfarm.cc/    let's add:
- Sun Requirements
- Spread (diameter)
- Row Spacing
- Height
We can do some practice on this. After we done and get some experience then we can add whatever we decide

So we can play with:
1. https://openfarm.cc/en/crops/strawberry
2. https://openfarm.cc/en/crops/orange
